import monstera from "../assets/monstera.jpg";
import ficus from "../assets/ficus.jpg";
import Pothos from "../assets/pothos.jpg";

export const plantList = [
  {
    name: "Monstera",
    category: "Classique",
    id: "1ed",
    isBestSale: true,
    light: 1,
    water: 3,
    waterComment:
      "Arrosez votre Monstera environ 1 fois par semaine au printemps et en été. En hiver, encore plus rarement. Il est indispensable de laisser sécher la terre entre chaque nouvel arrosage. Touchez-la du bout des doigts avant d’ajouter de l'eau. Si elle est humide, attendez encore quelques jours. Vous pouvez brumiser ses feuilles et ses racines avec un vaporisateur d’eau non calcaire, lorsque l’air est trop sec. Originaire des forêts tropicales humides, le Monstera a besoin de se sentir dans son environnement naturel pour prospérer.",
    cover: monstera,
    price: 12,
    description:
      "La discrétion, très peu pour lui ! Comme son nom l’indique, le Monstera sait imposer sa loi, notamment dans son milieu naturel où il se transforme en véritable liane grimpant le long des troncs des arbres. Il est à coup sûr un compagnon malin : il a su développer des grandes feuilles supérieures dentelées pour permettre à celles inférieures de capter la lumière du soleil. Imposant et sculptural, il existe en plusieurs variétés toutes plus belles les unes que les autres, comme le fameux Monstera Variegata au feuillage bicolore blanc et vert ou le Monstera Deliciosa (faux philodendron). Pas étonnant que cette plante d’intérieur particulièrement photogénique ait même lancé une nouvelle tendance très populaire sur Instagram avec son hashtag #monsteramonday. Vous êtes tombé sous le charme de cette beauté sauvage et tropicale ?",
    entretien:
      "Il ne faut pas couper les racines aériennes, mais vous pouvez tailler les tiges, en les pinçant à leur extrémité pour stopper la croissance et rafraîchir votre plante d'intérieur. Au printemps et en été, vous pouvez ajouter de l’engrais liquide environ 1 fois par mois. Aussi, il est nécessaire de le rempoter dès lors que les racines sont à l’étroit dans le pot. Les jeunes Monsteras en pot doivent être rempotés au printemps. Pratiquez un surfaçage en remplaçant la terre en surface par un nouveau terreau, si votre plante est déjà volumineuse.",
  },
  {
    name: "Ficus lyrata",
    category: "Classique",
    id: "2ab",
    isBestSale: true,
    light: 3,
    water: 3,
    cover: ficus,
    price: 4,
  },
  {
    name: "Pothos argenté",
    category: "Classique",
    id: "3sd",
    isBestSale: false,
    light: 3,
    water: 3,
    cover: Pothos,
    price: 8,
  },
  {
    name: "Yucca",
    category: "Classique",
    id: "4kk",
    isBestSale: false,
    light: 3,
    water: 3,
    cover: monstera,
    price: 5,
  },
  {
    name: "Olivier",
    category: "Extérieur",
    id: "5pl",
    isBestSale: false,
    light: 3,
    water: 3,
    cover: monstera,
    price: 13,
  },
  {
    name: "Géranium",
    category: "Extérieur",
    id: "6uo",
    isBestSale: false,
    light: 3,
    water: 3,
    cover: monstera,
    price: 15,
  },
  {
    name: "Basilique",
    category: "Extérieur",
    id: "7ie",
    isBestSale: false,
    light: 3,
    water: 3,
    cover: monstera,
    price: 17,
    isSpecialOffer: true,
  },
  {
    name: "Aloe",
    category: "Plante grasse",
    id: "8fp",
    isBestSale: false,
    light: 3,
    water: 2,
    cover: monstera,
    price: 10,
    isSpecialOffer: true,
  },
  {
    name: "Succulente",
    category: "Plante grasse",
    id: "9vn",
    isBestSale: false,
    light: 3,
    water: 1,
    cover: monstera,
    price: 11,
  },
];
